#!/bin/bash
# ==============================================================================
# loro-fuseki — Container entrypoint
# ==============================================================================
#
# This script:
#   1. Validates the admin password (other roles are optional).
#   2. Generates shiro.ini with three-role authentication (admin/app/read).
#   3. Optionally loads TTL files from /staging into Fuseki on first start.
#   4. Builds the Lucene full-text index if missing (after data load).
#   5. Starts Fuseki on $PORT in the foreground.
#
# Three-role model:
#   iacbx_read   — SPARQL query / Graph Store Protocol (read)
#   iacbx_app    — same as read + SPARQL Update / GSP write
#   iacbx_admin  — same as app + server admin (UI, /$/* admin API)
#
# ==============================================================================

set -e

# -- Defaults -----------------------------------------------------------------
PORT="${PORT:-8080}"
JVM_ARGS="${JVM_ARGS:--Xmx2g -Xms512m}"
FUSEKI_HOME="${FUSEKI_HOME:-/opt/fuseki}"
FUSEKI_BASE="${FUSEKI_BASE:-/fuseki}"
FUSEKI_READONLY="${FUSEKI_READONLY:-false}"
LOAD_DATA_ON_START="${LOAD_DATA_ON_START:-false}"
DATASET_NAME="loro"
STAGING_DIR="/staging"

# -- Credentials (from environment variables) ---------------------------------
IACBX_READ_PASSWORD="${IACBX_READ_PASSWORD:-}"
IACBX_APP_PASSWORD="${IACBX_APP_PASSWORD:-}"
IACBX_ADMIN_PASSWORD="${IACBX_ADMIN_PASSWORD:-}"

# -- Logging colors -----------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# ==============================================================================
# 1. Validate credentials
# ==============================================================================
validate_credentials() {
    if [ -z "${IACBX_ADMIN_PASSWORD}" ]; then
        log_error "IACBX_ADMIN_PASSWORD is not set (required to start the server)."
        log_error "Set it as an environment variable, e.g. via docker-compose .env."
        exit 1
    fi

    if [ -z "${IACBX_APP_PASSWORD}" ]; then
        log_warn "IACBX_APP_PASSWORD not set — iacbx_app user will not be available."
    fi

    if [ -z "${IACBX_READ_PASSWORD}" ]; then
        log_warn "IACBX_READ_PASSWORD not set — iacbx_read user will not be available."
    fi
}

# ==============================================================================
# 2. Generate shiro.ini
# ==============================================================================
generate_shiro() {
    local shiro_dir="${FUSEKI_BASE}/run"
    mkdir -p "${shiro_dir}"

    log_info "Generating Shiro security configuration"

    local users_section=""

    # iacbx_admin — always present (validated above)
    users_section+="iacbx_admin = ${IACBX_ADMIN_PASSWORD}, admin, app, read"
    users_section+=$'\n'
    log_info "  iacbx_admin configured (roles: admin, app, read)"

    # iacbx_app — only if password is set
    if [ -n "${IACBX_APP_PASSWORD}" ]; then
        users_section+="iacbx_app = ${IACBX_APP_PASSWORD}, app, read"
        users_section+=$'\n'
        log_info "  iacbx_app configured (roles: app, read)"
    fi

    # iacbx_read — only if password is set
    if [ -n "${IACBX_READ_PASSWORD}" ]; then
        users_section+="iacbx_read = ${IACBX_READ_PASSWORD}, read"
        users_section+=$'\n'
        log_info "  iacbx_read configured (roles: read)"
    fi

    cat > "${shiro_dir}/shiro.ini" <<EOF
# Apache Shiro security configuration — auto-generated by entrypoint.sh
# Do not edit manually; passwords are injected from environment variables.

[main]
ssl.enabled = false

# Session manager (required for Fuseki 5.6+ on Jetty 12)
sessionManager = org.apache.shiro.session.mgt.DefaultSessionManager
securityManager.sessionManager = \$sessionManager
securityManager.subjectDAO.sessionStorageEvaluator.sessionStorageEnabled = false

# HTTP Basic authentication
authcBasic = org.apache.shiro.web.filter.authc.BasicHttpAuthenticationFilter
authcBasic.applicationName = Apache Jena Fuseki — LoRO

[users]
${users_section}
[roles]
admin = *
app = *
read = *

[urls]
# Health endpoints — always public (so probes don't need credentials)
/\$/status  = anon
/\$/ping    = anon

# Server admin API — admin role only
/\$/\*\*    = authcBasic, roles[admin]

# SPARQL read endpoints — any of read/app/admin
/**/sparql  = authcBasic, roles[read]
/**/query   = authcBasic, roles[read]
/**/get     = authcBasic, roles[read]

# Write endpoints — app/admin
/**/update  = authcBasic, roles[app]
/**/data    = authcBasic, roles[app]

# Everything else (including the web UI) — admin only
/**         = authcBasic, roles[admin]
EOF

    log_info "Shiro configuration written to ${shiro_dir}/shiro.ini"
}

# ==============================================================================
# 3. Load TTL data from /staging (optional, runs on first start)
# ==============================================================================
load_staging_data() {
    local fuseki_url="http://localhost:${PORT}"
    local namespace_base="http://maia.madrid.es/ontologies/loro"
    local auth_user="iacbx_admin"
    local auth_pass="${IACBX_ADMIN_PASSWORD}"

    if [ ! -d "${STAGING_DIR}" ] || [ -z "$(ls -A ${STAGING_DIR}/*.ttl 2>/dev/null)" ]; then
        log_info "No TTL files found in ${STAGING_DIR}; skipping data load."
        return 0
    fi

    # Skip load if the database already has data
    local triple_count
    triple_count=$(curl -s -u "${auth_user}:${auth_pass}" \
        -X POST "${fuseki_url}/${DATASET_NAME}/sparql" \
        -H "Accept: application/sparql-results+json" \
        -d "query=SELECT (COUNT(*) AS ?c) WHERE { ?s ?p ?o }" 2>/dev/null | \
        grep -o '"value":"[0-9]*"' | head -1 | grep -o '[0-9]*' || echo "0")

    if [ "${triple_count}" -gt 0 ] 2>/dev/null; then
        log_info "Database already contains ${triple_count} triples; skipping data load."
        return 0
    fi

    log_info "Loading TTL files from ${STAGING_DIR}..."

    # Map of TTL file → named graph (last URI segment)
    declare -A GRAPH_MAP=(
        ["event.ttl"]="event"
        ["feature.ttl"]="feature"
        ["legal-resource.ttl"]="legal-resource"
        ["legal-resource-subdivision.ttl"]="legal-resource-subdivision"
        ["legal-value.ttl"]="legal-value"
        ["organization.ttl"]="organization"
        ["taxonomy.ttl"]="taxonomy"
        ["person.ttl"]="person"
        ["role.ttl"]="role"
    )

    local loaded=0
    local failed=0

    for file in "${!GRAPH_MAP[@]}"; do
        local filepath="${STAGING_DIR}/${file}"
        local graph_name="${GRAPH_MAP[$file]}"
        local graph_uri="${namespace_base}/${graph_name}"

        if [ -f "${filepath}" ]; then
            log_info "  Loading ${file} -> ${graph_uri}"
            local http_code
            http_code=$(curl -s -o /dev/null -w "%{http_code}" \
                -u "${auth_user}:${auth_pass}" \
                -X POST "${fuseki_url}/${DATASET_NAME}/data?graph=${graph_uri}" \
                -H "Content-Type: text/turtle" \
                --data-binary @"${filepath}")

            if [ "${http_code}" = "200" ] || [ "${http_code}" = "201" ] || [ "${http_code}" = "204" ]; then
                loaded=$((loaded + 1))
            else
                log_error "  Failed to load ${file} (HTTP ${http_code})"
                failed=$((failed + 1))
            fi
        fi
    done

    # Load the ontology if it is present (bundled in the image at /staging/ontology/loro.ttl)
    if [ -f "${STAGING_DIR}/ontology/loro.ttl" ]; then
        log_info "  Loading LoRO ontology -> ${namespace_base}/ontology"
        curl -s -o /dev/null \
            -u "${auth_user}:${auth_pass}" \
            -X POST "${fuseki_url}/${DATASET_NAME}/data?graph=${namespace_base}/ontology" \
            -H "Content-Type: text/turtle" \
            --data-binary @"${STAGING_DIR}/ontology/loro.ttl" || true
    fi

    log_info "Data load complete: ${loaded} graph(s) loaded, ${failed} failed."
}

# ==============================================================================
# 4. Build the Lucene full-text index (only if missing)
# ==============================================================================
build_text_index() {
    local lucene_dir="/fuseki/databases/loro-lucene"
    local assembler_config="${FUSEKI_BASE}/configuration/loro.ttl"

    if [ -d "${lucene_dir}" ] && [ -n "$(ls -A "${lucene_dir}" 2>/dev/null)" ]; then
        log_info "Lucene index already present at ${lucene_dir}; skipping rebuild."
        return 0
    fi

    log_info "Building Lucene full-text index..."
    java -cp "${FUSEKI_HOME}/fuseki-server.jar" jena.textindexer \
        --desc="${assembler_config}"
    log_info "Lucene index built at ${lucene_dir}"
}

# ==============================================================================
# 5. Start Fuseki
# ==============================================================================
start_fuseki() {
    log_info "============================================"
    log_info "loro-fuseki container starting"
    log_info "============================================"
    log_info "Port:           ${PORT}"
    log_info "FUSEKI_HOME:    ${FUSEKI_HOME}"
    log_info "FUSEKI_BASE:    ${FUSEKI_BASE}"
    log_info "JVM_ARGS:       ${JVM_ARGS}"
    log_info "Read-only:      ${FUSEKI_READONLY}"
    log_info "Auto-load data: ${LOAD_DATA_ON_START}"
    log_info "Active users:   iacbx_admin$([ -n "${IACBX_APP_PASSWORD}" ] && echo ', iacbx_app')$([ -n "${IACBX_READ_PASSWORD}" ] && echo ', iacbx_read')"
    log_info "============================================"

    validate_credentials
    generate_shiro

    if [ "${LOAD_DATA_ON_START}" = "true" ]; then
        # Start Fuseki in the background to allow data ingestion via HTTP
        log_info "Starting Fuseki in the background to load data..."
        java ${JVM_ARGS} \
            -DFUSEKI_HOME="${FUSEKI_HOME}" \
            -DFUSEKI_BASE="${FUSEKI_BASE}" \
            -jar "${FUSEKI_HOME}/fuseki-server.jar" \
            --port="${PORT}" &
        FUSEKI_PID=$!

        # Wait until Fuseki responds to /ping
        log_info "Waiting for Fuseki to become available..."
        for i in $(seq 1 60); do
            if curl -sf "http://localhost:${PORT}/$/ping" > /dev/null 2>&1; then
                log_info "Fuseki is up after ${i}s"
                break
            fi
            if [ "$i" -eq 60 ]; then
                log_error "Fuseki did not start within 60s"
                exit 1
            fi
            sleep 1
        done

        load_staging_data

        # Stop Fuseki to build the Lucene index (textindexer needs an exclusive lock)
        log_info "Stopping Fuseki to (re)build Lucene index if necessary..."
        kill ${FUSEKI_PID}
        wait ${FUSEKI_PID} 2>/dev/null || true

        build_text_index

        log_info "Restarting Fuseki in the foreground on port ${PORT}..."
        exec java ${JVM_ARGS} \
            -DFUSEKI_HOME="${FUSEKI_HOME}" \
            -DFUSEKI_BASE="${FUSEKI_BASE}" \
            -jar "${FUSEKI_HOME}/fuseki-server.jar" \
            --port="${PORT}"
    else
        log_info "Starting Fuseki in the foreground on port ${PORT}..."
        exec java ${JVM_ARGS} \
            -DFUSEKI_HOME="${FUSEKI_HOME}" \
            -DFUSEKI_BASE="${FUSEKI_BASE}" \
            -jar "${FUSEKI_HOME}/fuseki-server.jar" \
            --port="${PORT}"
    fi
}

# -- Main ---------------------------------------------------------------------
start_fuseki
